language: python
python:
  - '3.5'

services:
  - docker

before_install:
- docker build --pull --force-rm --tag schemigrator:latest .
- docker run --name schemigrator -p 13300:10000 -p 13301:10001 -p 13302:10002 -p 13303:10003 --detach schemigrator:latest
- docker ps -a
- eval 'while true; do healthy=$(docker inspect --format "{{.State.Health.Status}}" schemigrator); if [ "x$healthy" == "xhealthy" ]; then break; fi; sleep 1; done'

script:
- pytest --cov=./ . || pytest --cov=./ .

after_success:
- codecov --token=dcfbd16d-46c0-475c-9463-ad3e2e6b926b